### ISSUE TITLE
Add support for cryptocurrency pairs?

### ISSUE THREAD

**Issue by nopynoop** [BarRaider/streamdeck-stockticker#1]
I really like this plugin and appreciate the amount of work you into your plugin projects.

It would be really awesome to maybe add cryptocurrencies/USD pair support.

Thanks and keep up the good work.

**Comment by BarRaider** [comment]
Hi,

If you know of a free API that can get this information, please contact me on my Discord server. Link can be found at https://barraider.github.io/

**Comment by d-rez** [comment]
Commenting here as I don't want to duplicate threads

How about Independent Reserve API?
https://www.independentreserve.com/api

**Comment by BarRaider** [comment]
@nopynoop @d-rez 
As I'm less into crypto trading - How is this one?
https://api.binance.com/api/v1/ticker/24hr
(I know it's in Json but notice there are a lot of different currencies). Is it better than the one @d-rez  mentioned above?

**Comment by nopynoop** [comment]
Good find. The official Binance API looks good and it could be a great addition to your existing plugin.

**Comment by BarRaider** [comment]
Hi @nopynoop @d-rez , I have a pre-release version you can try out.
Ping me at my discord server. Contact info at https://barraider.github.io
