### ISSUE TITLE
Too many calls from streamdeck-stockticker (BTC/USD)

### ISSUE THREAD

**Issue by nopynoop** [BarRaider/streamdeck-stockticker#20]
I think the API is being called way too frequently.

I think the interval shouldn't be below 5min.

This is the data usage for Today and I only check the BTC / USD pair:
![Q6flue3t](https://user-images.githubusercontent.com/25570106/66703152-c4967d80-ed0f-11e9-96f6-3c2403a3eaef.png)
![x888](https://user-images.githubusercontent.com/25570106/66703188-1b03bc00-ed10-11e9-9a53-eb244fe5a84f.png)

**Comment by BarRaider** [comment]
Refresh interval is once a minute. That's by design
